### ISSUE TITLE
Would love to get formatter support on save

### ISSUE THREAD

**Issue by matanyall** [grafana/vscode-alloy#3]
Hey y'all,

I know you guys already have `alloy fmt`, so It shouldn't be difficult to have that command added as a formatter option, so we can format on save. I've never implemented it before, but might be able to take a crack if no one else want's to. Cheers!

**Comment by rfratto** [comment]
I also think this would be great! I don't think I'll have time to implement this for a while so others are definitely free to take a crack at it :)

**Comment by matanyall** [comment]
Gave it a shot in #4

**Comment by rfratto** [comment]
Implemented in #4
