### ISSUE TITLE
keep getting  Alloy is not installed error after install

### ISSUE THREAD

**Issue by yosiasz** [grafana/vscode-alloy#7]
Windows 10 Enterprise

vs code

![image](https://github.com/user-attachments/assets/4a6cc64a-6ac4-4463-aea5-0eec40175cd3)

Error
![image](https://github.com/user-attachments/assets/92a48a89-2705-4934-8f67-412758e6d66b)

**Comment by cardasac** [comment]
I had the same issue and I believe you need to install alloy locally as well [Install alloy](https://grafana.com/docs/alloy/latest/set-up/install/).

**Comment by yosiasz** [comment]
looks like that error message is a red herring. it still works in vscode, even with alloy-installer-windows-amd64.exe.zip not installed.
